apiVersion: v2
name: devops-app
description: A Helm chart for the DevOps Pipeline Demo application

type: application

version: 0.1.0

appVersion: "1.0.0"

maintainers:
  - name: DevOps Team
    email: devops@example.com
