apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  labels:
    app: devops-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: devops-demo
